name: SonarQube Analysis
on: [push]
jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/analysis-scanner
      with:
          # The URL of your SonarQube server
          sonarqube-host-url: ${{ secrets.SONAR_HOST_URL }}
          # The token used to authenticate with the SonarQube server
          sonarqube-token: ${{ secrets.SONAR_TOKEN }}
    - name: SonarQube Quality Gate Check
      uses: SonarSource/sonarqube-quality-gate-action@v1.0.0